### PR TITLE
Do autogeneration at build-time; prepare for 0.8.0 release

### PR DESCRIPTION
**Pull request by thomassa**

### CODE REVIEW

**Comment by thomassa** [comment]
This will need a corresponding change in the xen-api-libs-specs repository.

**Comment by thomassa** [comment]
The third commit is an attempt at a fix for the first one; if it works I shall squash those two together.

**Comment by jonludlam** [comment]
Your makefile looks wrong. I think you need a setup.ml target. You're currently relying on it in the setup.data target but only generating it in the build target, which depends upon setup.data.

**Comment by simonjbeaumont** [comment]
If you want a Makefile that will work you can add DevTools to your `_oasis` file and use `oasis setup -setup-update dynamic`. Or even just `oasis setup` and add an extra target for `setup.ml`:
```make
setup.ml:
    oasis setup
```

**Comment by thomassa** [comment]
This builds fine in build.hg but the travis build fails because it is not yet using the new xen-api-libs-specs.

**Comment by thomassa** [comment]
Once things are sorted such that travis will use the current xen-api-libs-specs, I shall push the squashed version of these commits.

**Comment by thomassa** [comment]
Travis-build passed.
So now this pullreq is ready for review and (I hope) merge.

**Comment by jonludlam** [comment]
I don't quite get the green ticks - looks like it's on the penultimate commit?

**Pull request merged**
