### PR TITLE
CA-236851: Experimental: Aggresively close VHDs after reading the BAT

### PR DESCRIPTION
**Pull request by jonludlam**
Signed-off-by: Jon Ludlam <jonathan.ludlam@citrix.com>

### CODE REVIEW

**Comment by djs55** [comment]
Dare I ask what went wrong?

**Comment by jonludlam** [comment]
Sure - it seems that without this we had the LVs open for the entire duration of the copy, which isn't necessary since we've loaded the BATs and never read from the VHDs directly again. This interfered with some LV refreshes that were happening as a result of coalesce operations.

**Comment by djs55** [comment]
Thanks for the explanation!

**Comment by robhoes** [comment]
Dare I say that the explanation deserved to be in the commit message...? ;)

**Pull request merged**
