### PR TITLE
CA-290243: avoid high memory usage during copying from NBD device

### PR DESCRIPTION
**Pull request by gaborigloi**
Only 2edf06d  is important.

### CODE REVIEW

**Comment by gaborigloi** [comment]
The quicktests passed.

**Comment by gaborigloi** [comment]
As for integer overflows, they cannot happen in Python as far as I know, and probably nor will they happen in OCaml, because we're working with 64-bit ints, so we'd need a disk of size greater than `9223372036854775807L` to overflow - that'd be a huge disk, that we don't currently support.

**Comment by edwintorok** [comment]
I agree that extents have to be non-overlapping, but what if your extent is larger than the requested area, like in my example where one extent finishes 4K before offset+length, and next extent starts at offset+length-4k and extents until offset+length+60K? Will you split the extent?

**Comment by gaborigloi** [comment]
The script must return extents that exactly cover the requested area.

**Comment by edwintorok** [comment]
ok, so you'll need to update the script to do that right?

**Comment by gaborigloi** [comment]
No, the script already works that way.

**Comment by edwintorok** [comment]
request_len = min(MAX_REQUEST_LEN, size - offset)
             replies = client.query_block_status(offset, request_len)

**Comment by edwintorok** [comment]
Ok, is it because you limit the request length here, and the NBD protocol guarantees it returns extents that match exactly?
```
        request_len = min(MAX_REQUEST_LEN, size - offset)
         replies = client.query_block_status(offset, request_len)
```

**Comment by gaborigloi** [comment]
Yes:
```
The list of block status descriptors within the NBD_REPLY_TYPE_BLOCK_STATUS chunk represent consecutive portions of the file starting from specified offset, and the sum of the length fields of each descriptor MUST not be greater than the overall length of the request.
```
https://github.com/NetworkBlockDevice/nbd/blob/extension-blockstatus/doc/proto.md

So we might get back less, but never more at the moment. If we get back less, the script will keep looping until we've covered the entire area.

**Pull request merged**
